/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoRouteImport } from './routes/video'
import { Route as SpecialRouteImport } from './routes/special'
import { Route as SecretRouteImport } from './routes/secret'
import { Route as RoastRouteImport } from './routes/roast'
import { Route as RevealRouteImport } from './routes/reveal'
import { Route as ReelRouteImport } from './routes/reel'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FinalRouteImport } from './routes/final'
import { Route as CertificateRouteImport } from './routes/certificate'
import { Route as IndexRouteImport } from './routes/index'

const VideoRoute = VideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialRoute = SpecialRouteImport.update({
  id: '/special',
  path: '/special',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretRoute = SecretRouteImport.update({
  id: '/secret',
  path: '/secret',
  getParentRoute: () => rootRouteImport,
} as any)
const RoastRoute = RoastRouteImport.update({
  id: '/roast',
  path: '/roast',
  getParentRoute: () => rootRouteImport,
} as any)
const RevealRoute = RevealRouteImport.update({
  id: '/reveal',
  path: '/reveal',
  getParentRoute: () => rootRouteImport,
} as any)
const ReelRoute = ReelRouteImport.update({
  id: '/reel',
  path: '/reel',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FinalRoute = FinalRouteImport.update({
  id: '/final',
  path: '/final',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificateRoute = CertificateRouteImport.update({
  id: '/certificate',
  path: '/certificate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/certificate': typeof CertificateRoute
  '/final': typeof FinalRoute
  '/gallery': typeof GalleryRoute
  '/reel': typeof ReelRoute
  '/reveal': typeof RevealRoute
  '/roast': typeof RoastRoute
  '/secret': typeof SecretRoute
  '/special': typeof SpecialRoute
  '/video': typeof VideoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/certificate': typeof CertificateRoute
  '/final': typeof FinalRoute
  '/gallery': typeof GalleryRoute
  '/reel': typeof ReelRoute
  '/reveal': typeof RevealRoute
  '/roast': typeof RoastRoute
  '/secret': typeof SecretRoute
  '/special': typeof SpecialRoute
  '/video': typeof VideoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/certificate': typeof CertificateRoute
  '/final': typeof FinalRoute
  '/gallery': typeof GalleryRoute
  '/reel': typeof ReelRoute
  '/reveal': typeof RevealRoute
  '/roast': typeof RoastRoute
  '/secret': typeof SecretRoute
  '/special': typeof SpecialRoute
  '/video': typeof VideoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/certificate'
    | '/final'
    | '/gallery'
    | '/reel'
    | '/reveal'
    | '/roast'
    | '/secret'
    | '/special'
    | '/video'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/certificate'
    | '/final'
    | '/gallery'
    | '/reel'
    | '/reveal'
    | '/roast'
    | '/secret'
    | '/special'
    | '/video'
  id:
    | '__root__'
    | '/'
    | '/certificate'
    | '/final'
    | '/gallery'
    | '/reel'
    | '/reveal'
    | '/roast'
    | '/secret'
    | '/special'
    | '/video'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CertificateRoute: typeof CertificateRoute
  FinalRoute: typeof FinalRoute
  GalleryRoute: typeof GalleryRoute
  ReelRoute: typeof ReelRoute
  RevealRoute: typeof RevealRoute
  RoastRoute: typeof RoastRoute
  SecretRoute: typeof SecretRoute
  SpecialRoute: typeof SpecialRoute
  VideoRoute: typeof VideoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video': {
      id: '/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/special': {
      id: '/special'
      path: '/special'
      fullPath: '/special'
      preLoaderRoute: typeof SpecialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secret': {
      id: '/secret'
      path: '/secret'
      fullPath: '/secret'
      preLoaderRoute: typeof SecretRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roast': {
      id: '/roast'
      path: '/roast'
      fullPath: '/roast'
      preLoaderRoute: typeof RoastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reveal': {
      id: '/reveal'
      path: '/reveal'
      fullPath: '/reveal'
      preLoaderRoute: typeof RevealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reel': {
      id: '/reel'
      path: '/reel'
      fullPath: '/reel'
      preLoaderRoute: typeof ReelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/final': {
      id: '/final'
      path: '/final'
      fullPath: '/final'
      preLoaderRoute: typeof FinalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate': {
      id: '/certificate'
      path: '/certificate'
      fullPath: '/certificate'
      preLoaderRoute: typeof CertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CertificateRoute: CertificateRoute,
  FinalRoute: FinalRoute,
  GalleryRoute: GalleryRoute,
  ReelRoute: ReelRoute,
  RevealRoute: RevealRoute,
  RoastRoute: RoastRoute,
  SecretRoute: SecretRoute,
  SpecialRoute: SpecialRoute,
  VideoRoute: VideoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
